
const infomakanan = [
  {
      id: 0,
      name: "Raminten",
      imgURL: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/indizone/2022/07/27/Ens8Bl5/house-of-raminten-rekomendasi-kafe-enggak-biasa-di-yogyakarta-suasananya-jawa-banget64.jpg",
      title0: "Restoran Budaya",
      title1: "Menjadi Tempat Belajar",
      title2: "Penampakan lokasi",
      title3: "",
      title4: "",
      title5: "",
      description1: 'Tempat makan Raminten, yang terletak di Jogja, tidak hanya sekadar restoran, tetapi juga sebuah pengalaman budaya yang menyeluruh. Begitu memasuki tempat ini, pengunjung disambut dengan dekorasi tradisional Jawa yang kental, mulai dari lampu-lampu antik hingga dekorasi dinding yang khas. Suasana yang hangat dan ramah membuat setiap kunjungan terasa seperti pulang ke rumah nenek di desa. Di sini, pengunjung dapat menikmati beragam hidangan khas Jawa yang disajikan dalam suasana yang autentik. Mulai dari soto, nasi campur, gudeg, hingga wedang jahe, semua hidangan disajikan dengan cita rasa yang otentik dan kaya akan rempah-rempah. Selain itu, tempat makan Raminten juga seringkali menyelenggarakan pertunjukan seni tradisional Jawa seperti wayang kulit atau musik gamelan, sehingga pengunjung tidak hanya dimanjakan dengan makanan lezat, tetapi juga dengan hiburan budaya yang memikat.',
      description2: 'Selain itu, tempat makan Raminten juga menjadi tempat yang cocok untuk belajar dan mengeksplorasi kebudayaan Jawa. Di sela-sela menikmati hidangan lezat, pengunjung dapat menemukan berbagai macam artefak budaya Jawa yang dipajang di sekitar restoran. Mulai dari wayang kulit hingga batik, setiap sudut restoran dipenuhi dengan kekayaan budaya Jawa yang menarik untuk dipelajari. Para karyawan yang ramah dan berpengetahuan luas tentang budaya lokal juga siap memberikan informasi dan cerita menarik tentang setiap artefak yang ada. Dengan begitu, makan di Raminten bukan hanya sekadar memuaskan selera, tetapi juga mengajak pengunjung untuk menjelajahi dan menghargai keindahan serta kekayaan budaya Jawa yang tiada taranya.',
      description3: "Jl. Faridan M Noto No.7, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224",
      img1: "https://raminten.com/wp-content/uploads/2022/06/sky-768x432.jpg.webp",
      vidURL: "https://www.youtube.com/embed/6FVbNfGlaYM?si=ZwcWcvtLBUHKYre8",
      vidTitle: "",
      alamat: "Jl. Faridan M Noto No.7, Kotabaru, Kec. Gondokusuman, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55224",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.043786213962!2d110.368816175005!3d-7.785182592234596!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5831e4074603%3A0xbf9157808e91c603!2sThe%20House%20of%20Raminten!5e0!3m2!1sen!2sid!4v1716062914789!5m2!1sen!2sid'
    },
    {
      id: 1,
      name: "Kopi Klotok",
      imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8M_9HVJX8TE7I06wGYTtabJs0NMhLN5bYEZKwIFdktg&s",
      title1: "Keunikan",
      title2: "Penampakan Lokasi",
      // title3: "Kirab Pengantin",
      description1: 'Kopi Klotok adalah tempat kopi yang unik di Jogja yang menawarkan pengalaman minum kopi yang berbeda dari kebanyakan kedai kopi lainnya. Terletak di salah satu sudut yang tenang di tengah hiruk pikuknya Kota Yogyakarta, tempat ini menghadirkan suasana yang nyaman dan santai bagi para pengunjungnya. Dengan dekorasi yang sederhana namun hangat, Kopi Klotok menjadi tempat yang ideal untuk bersantai sambil menikmati secangkir kopi yang segar.      ',
      description2: 'Selain menyajikan kopi berkualitas tinggi dari biji kopi pilihan, Kopi Klotok juga dikenal karena menyediakan menu kopi dengan sentuhan lokal yang unik, seperti kopi Joss yang terkenal atau kopi tubruk khas Jawa. Pengunjung juga dapat menemukan berbagai variasi kopi dari berbagai daerah di Indonesia, yang semuanya disajikan dengan penuh keahlian dan kecintaan terhadap kopi. Dengan suasana yang ramah dan layanan yang baik, Kopi Klotok menjadi tempat yang sempurna bagi para pecinta kopi untuk menikmati kelezatan kopi sambil menikmati pesona kota budaya Yogyakarta.      ',
      description3: "Jalan Kaliurang No.KM.16, Area Sawah, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582",
      // description4: 'Pawai atau arak-arakan yang membawa jali pengantin bekakak ke tempat penyembelihan Selain itu, Patran membawa rangkaian sesaji sugengan Ageng ke pesanggrahan. Selain itu, mereka diarak ke balai desa terlebih dahulu. Urut-urutan arakan atau pawai ritual adalah sebagai berikut: Reyog dan jathilan dari Patran Sesaji sugengan Ageng Barisan prajurit dari Gamping tengah membawa umbul-umbul memakai celana hitam kagok, berkain, baju lurik, destalan, seperti prajurit Daeng. Mereka membawa seruling, genderang dan mung-mung, dan lain-lain.',
      img1: "https://www.magnetoholidays.id/wp-content/uploads/2022/08/kopi-klotok.jpg",
      // img2: "https://www.magnetoholidays.id/wp-content/uploads/2022/08/kopi-klotok.jpg",
      vidURL: "https://www.youtube.com/embed/lNadRArbSok?si=NKEseBtKp8ZQruKn",
      vidTitle: "",
      alamat: "Jalan Kaliurang No.KM.16, Area Sawah, Pakembinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3954.119102160474!2d110.4187311750038!3d-7.670342892346369!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5e80a3df1d61%3A0x3c02536343f1185c!2sKlotok%20Coffeshop!5e0!3m2!1sen!2sid!4v1716063297682!5m2!1sen!2sid'
    },
    {
      id: 2,
      name: "Iga Bajog",
      imgURL: "https://asset-2.tstatic.net/tribunnews/foto/bank/images/iga-bakar-jogja-iga-bajog.jpg",
      title0: "Dekorasi yang Sederhana namun Nyaman",
      title1: "Menu Utama dan Keunikan",
      title2: "Salah satu Menu Utama",
      title3: "Penampakan Lokasi",
      description1: 'Iga Bajog adalah tempat makan yang terkenal di Jogja dengan spesialisasi dalam menyajikan hidangan iga sapi yang lezat dan menggugah selera. Terletak di pusat kota Yogyakarta, tempat ini menawarkan pengalaman kuliner yang memuaskan bagi para pengunjung yang menyukai masakan daging sapi yang lembut dan beraroma kaya. Dengan dekorasi yang sederhana namun nyaman, Iga Bajog memberikan suasana yang hangat dan ramah bagi setiap pengunjungnya.      ',
      description2: 'Menu utama di Iga Bajog adalah berbagai macam hidangan iga sapi, mulai dari iga bakar, iga goreng, hingga iga soup yang gurih. Selain itu, tempat ini juga menyajikan beragam hidangan pendamping yang cocok untuk dinikmati bersama dengan iga, seperti nasi putih, lalapan, dan sambal yang pedas. Dengan cita rasa yang autentik dan harga yang terjangkau, Iga Bajog menjadi pilihan yang populer bagi wisatawan dan penduduk lokal yang ingin menikmati santapan yang memuaskan di tengah kesibukan kota Jogja.      ',
      description3: "Berbagai macam iga sapi sebagai menu utama dari Iga Bajog.",
      description4: 'Sanggrahan, Jl. Ring Road Utara No.1, RW.2, Sanggrahan, Condongcatur, Depok, Sleman Regency, Special Region of Yogyakarta 55281',
      // description5: 'Gerakan Tarian Srimpi sangat lembut dan halus, mencerminkan karakter perempuan Jawa yang anggun dan penuh kesabaran. Setiap gerakan dalam tarian ini dilakukan dengan sangat hati-hati dan penuh perhitungan, menunjukkan keindahan dalam kesederhanaan dan ketenangan. Tarian ini sering dibawakan oleh empat penari, yang melambangkan keseimbangan empat elemen alam (tanah, air, api, dan udara) atau empat penjuru mata angin. Keselarasan antara penari juga mencerminkan pentingnya harmoni dan kerjasama dalam kehidupan. Tarian Srimpi biasanya menceritakan kisah-kisah dari epos Ramayana dan Mahabharata, yang mengandung banyak pesan moral dan nilai-nilai kehidupan. Cerita-cerita ini sering mengajarkan tentang kebaikan melawan kejahatan, kesetiaan, keberanian, dan kebijaksanaan. Dalam filosofinya, Tarian Srimpi mengandung konsep "penyatuan rasa", di mana penari dan penonton diharapkan dapat merasakan dan memahami esensi dari tarian tersebut. Ini merupakan bentuk meditasi dan refleksi bersama yang mendalam. Melalui Tarian Srimpi, nilai-nilai budaya, sejarah, dan spiritualitas Jawa dapat dilestarikan dan diwariskan dari generasi ke generasi. Tarian ini bukan hanya sekedar seni pertunjukan, tetapi juga cerminan dari kearifan lokal dan pandangan hidup masyarakat Jawa.',
      img1: "https://gudeg.net/cni-content/uploads/modules/posts/thumbs/medium/20210304062600.png",
      img2: "https://cdn.idntimes.com/content-images/community/2023/09/img-20230727-wa0039-84f809aacc26805e68e207e50a170f3e-7311174302e2898caefb4ccd77bdb9f0.jpg",
      vidURL: "https://www.youtube.com/embed/eQbzok3HU_A?si=trnzegMj3Y9f2xHQ",
      vidTitle: "Penjelasan Iga Bajog oleh Om Anya Review",
      alamat: "Sanggrahan, Jl. Ring Road Utara No.1, RW.2, Sanggrahan, Condongcatur, Depok, Sleman Regency, Special Region of Yogyakarta 55281",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.2980584549973!2d110.39604779999999!3d-7.7581798!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a595141e7b463%3A0xe6ab25fb7b035dfd!2sIga%20BAJOG%20(Iga%20Bakar%20Jogja)!5e0!3m2!1sen!2sid!4v1716063969338!5m2!1sen!2sid'
    },
    {
      id: 3,
      name: "Tempo Gelato",
      imgURL: "https://asset.kompas.com/crops/xQ8wNfXPXLMljhpr1cbijx-CogY=/0x58:700x525/750x500/data/photo/2020/01/17/5e2182942961b.jpeg",
      title0: "Destinasi bagi Pencinta Es Krim",
      title1: "Variasi Menu",
      title2: "Penampilan Depan",
      // title3: "Keunikan Rumah Adat Joglo",
      description1: 'Tempo Gelato adalah destinasi yang sempurna bagi para pecinta es krim di Jogja, yang menawarkan berbagai macam varian es krim segar dengan rasa yang autentik dan tekstur yang lembut. Terletak di jantung Kota Yogyakarta, Tempo Gelato menarik perhatian dengan dekorasi yang ceria dan atmosfir yang menyenangkan. Dengan desain interior yang modern namun tetap nyaman, tempat ini menjadi tempat yang ideal untuk bersantai sambil menikmati sepiring es krim yang lezat.      ',
      description2: 'Menu Tempo Gelato menawarkan beragam pilihan rasa yang menggugah selera, mulai dari rasa klasik seperti vanilla dan cokelat hingga pilihan eksotis seperti durian atau stroberi. Selain es krim, tempat ini juga menyajikan berbagai minuman dingin yang menyegarkan, seperti milkshake dan frappe. Dengan bahan-bahan berkualitas tinggi dan proses pembuatan yang terampil, setiap suapannya membawa pengalaman yang memuaskan bagi para penikmatnya. Tempo Gelato menjadi tempat yang populer bagi para pengunjung yang ingin menikmati camilan manis di tengah-tengah eksplorasi mereka di Kota Yogyakarta.      ',
      description3: "Kaliurang St No.KM.5 No.98, Kocoran, Sinduadi, Mlati, Sleman Regency, Special Region of Yogyakarta 55284      ",
      img0: "https://halalstyle.com/trend/assets/uploads/5B5F6322-030C-4389-82C5-5CD8B283A40E.jpeg",
      img1: "https://i0.wp.com/media.dekoruma.com/article/2021/08/18105708/rlm3a-Rumah-Limasan-Semar-Tinandhu.jpg?fit=950%2C631&ssl=1",
      img2: "",
      vidURL: "https://www.youtube.com/embed/g76UbjWs_5s?si=V0NUHQCjncbU6q7D",
      vidTitle: "Review Tempo Gelato oleh Syeni Channel",
      alamat: "Kaliurang St No.KM.5 No.98, Kocoran, Sinduadi, Mlati, Sleman Regency, Special Region of Yogyakarta 55284      ",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.255393328049!2d110.3796997!3d-7.762717200000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a59ac8eba7b9b%3A0xa481b43442a601bc!2sTempo%20Gelato%20Kaliurang!5e0!3m2!1sen!2sid!4v1716064287799!5m2!1sen!2sid'
    },
    {
      id: 4,
      name: "Gudeg Sagan",
      imgURL: "https://rentalmobiljogja.id/wp-content/uploads/2017/09/gudeg-sagan-01-1080x1036.jpg",
      title0: "",
      title1: "Menu Utama",
      title2: "Penampakan Lokasi",
      description1: 'Gudeg Sagan adalah salah satu destinasi kuliner yang terkenal di Jogja, khususnya bagi pecinta kuliner khas Jawa. Terletak di daerah Sagan, tempat ini menjadi favorit bagi wisatawan maupun penduduk lokal yang ingin menikmati hidangan gudeg yang autentik. Suasana warung yang sederhana namun ramai menciptakan pengalaman makan yang bersahaja namun berkesan bagi setiap pengunjung.',
      description2: 'Menu utama di Gudeg Sagan tentu saja adalah gudeg, hidangan khas Yogyakarta yang terbuat dari nangka muda yang dimasak dengan santan dan rempah-rempah, disajikan dengan telur, ayam, dan sambal. Selain itu, tempat ini juga menyediakan berbagai hidangan pendamping lainnya seperti ayam goreng, tempe, dan tahu bacem. Dengan cita rasa yang otentik dan harga yang terjangkau, Gudeg Sagan menjadi tempat yang wajib dikunjungi bagi mereka yang ingin merasakan kelezatan gudeg dalam suasana yang hangat dan ramah.      ',
      description3: 'JL Prof. Dr Jl. Prof. Herman Yohanes No.53, Samirono, Caturtunggal, Depok, Sleman Regency, Special Region of Yogyakarta 55223      ',
      img1: "https://halallife.id/media/2021/10/Sagan-2-1024x547.jpg",
      img2: "",
      vidURL: "https://www.youtube.com/embed/kKXvlu52PbY?si=ZWL6X6qwMPtX3Xmn",
      vidTitle: "Gudeg Sagan oleh Piknik Woii Channel",
      alamat: "JL Prof. Dr Jl. Prof. Herman Yohanes No.53, Samirono, Caturtunggal, Depok, Sleman Regency, Special Region of Yogyakarta 55223",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.112279702271!2d110.37977579999999!3d-7.777918000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a59544224e1b5%3A0x365766c4d68021d9!2sGudeg%20Sagan!5e0!3m2!1sen!2sid!4v1716064641423!5m2!1sen!2sid'
    },
    {
      id: 5,
      name: "Tahu Gimbal",
      imgURL: "https://asset-2.tstatic.net/tribunnewswiki/foto/bank/images/tahu-gimbal.jpg",
      title0: "",
      title1: "Menu Utama",
      title2: "Alamat",
      description1: 'Tahu Gimbal adalah salah satu warung makan legendaris di Jogja yang terkenal dengan hidangan khasnya yang unik dan lezat. Terletak di sudut-sudut kota yang ramai, warung ini menarik perhatian dengan aroma harum dan kesibukan para penjual yang menggoreng tahu di tempat. Suasana sederhana namun hidangan yang menggugah selera menciptakan pengalaman makan yang tak terlupakan bagi setiap pengunjung.      ',
      description2: 'Menu utama di Tahu Gimbal adalah tahu yang digoreng garing dengan tambahan potongan kol, tauge, dan lentho (bakso udang) yang disajikan dengan kuah kental yang gurih dan sambal pedas yang menyegarkan. Hidangan ini sangat populer di kalangan penduduk lokal maupun wisatawan yang mencari   camilan tradisional yang nikmat dan berisi. Dengan cita rasa yang khas dan harga yang terjangkau, Tahu Gimbal menjadi tempat favorit untuk menikmati hidangan khas Jogja yang otentik.',
      description3: 'Jl. Tentara Rakyat Mataram No.35, Bumijo, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55231      ',
      vidURL: 'https://www.youtube.com/embed/kUTJk4qN5qk?si=6GmgfMLNlNLIhcQA',
      alamat: 'Jl. Tentara Rakyat Mataram No.35, Bumijo, Kec. Jetis, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55231',
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.029046976795!2d110.35488237492!3d-7.786744992233091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5822d76d5e61%3A0xf3a546ad0611a458!2sJl.%20Tentara%20Rakyat%20Mataram%20No.35%2C%20Bumijo%2C%20Kec.%20Jetis%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta%2055231!5e0!3m2!1sen!2sid!4v1716065118565!5m2!1sen!2sid',
      vidTitle: 'Video oleh TRANS7',
    },
    {
      id: 6,
      name: "Bakmi Jawa",
      imgURL: "https://guide.horego.com/wp-content/uploads/2024/01/bakmi-jawa-di-semarang.jpg",
      title0: "",
      title1: "Menu Utama",
      title2: "Alamat",
      description1: 'Salah satu destinasi kuliner yang terkenal di Jogja adalah warung makan Bakmi Jawa, yang menawarkan hidangan mi tradisional dengan cita rasa khas Jawa. Terletak di berbagai sudut kota, warung-warung ini sering kali menarik perhatian dengan aroma harum bumbu rempah yang sedang dimasak dan suasana yang ramai dengan para pengunjung yang menikmati hidangan mereka. Dekorasi sederhana namun hangat menciptakan suasana yang nyaman bagi para pelanggan',      
      description2: 'Menu utama di warung Bakmi Jawa adalah mie rebus yang disajikan dengan kuah gurih, dilengkapi dengan irisan daging ayam atau sapi, sayuran segar seperti sawi dan tauge, serta taburan bawang goreng dan seledri yang segar. Selain mie rebus, beberapa warung juga menyajikan mie goreng yang disajikan dengan berbagai pilihan topping seperti telur, bakso, dan daging sapi cincang. Hidangan ini menjadi favorit di kalangan penduduk lokal dan wisatawan yang mencari rasa autentik dari masakan Jawa yang lezat dan memuaskan.      ',
      description3: 'Jl. Nyi Ageng Nis No.9, Rejowinangun, Kec. Kotagede, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55171      ',
      vidURL: 'https://www.youtube.com/embed/jJjOOo7bSAM?si=mHCQ3mEcVk6ea7Dd',
      alamat: 'Jl. Nyi Ageng Nis No.9, Rejowinangun, Kec. Kotagede, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55171      ',
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.7784467457664!2d110.39454117492025!3d-7.813261792207288!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a576b657120af%3A0xee87eef4c3d2c3cd!2sJl.%20Nyi%20Ageng%20Nis%20No.9%2C%20Rejowinangun%2C%20Kec.%20Kotagede%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta%2055171!5e0!3m2!1sen!2sid!4v1716065488090!5m2!1sen!2sid',
      vidTitle: 'RESEP BAKMI JAWA / MIE GODOG JAWA | UENAKKK POLLL WAJIB COBA oleh Ika Mardatillah',
    }
];

export default infomakanan;
