
const infowisata = [
  {
    id: 0,
    name: "Candi Prambanan",
    imgURL: "https://visitjawatengah.jatengprov.go.id/assets/images/3c3552b6-6934-4574-ba67-0445eaba6861.jpg",
    title1: "Harga tiket masuk Candi Prambanan",
    title2: "Asal-usul dan Sejarah",
    title0: "Sejarah Singkat",
    description1: 'Candi Prambanan, juga dikenal sebagai Candi Rara Jonggrang, adalah kompleks candi Hindu terbesar di Indonesia yang terletak di daerah Yogyakarta. Candi ini dibangun pada abad ke-9 dan didedikasikan untuk Trimurti, tiga dewa utama dalam agama Hindu: Brahma Sang Pencipta, Wisnu Sang Pemelihara, dan Siwa Sang Penghancur.',
    description2: "Per Mei 2024, harga tiket masuk Candi Prambanan adalah IDR 50,000 untuk dewasa domestik dan IDR 25,000 untuk anak-anak domestik usia 3-10 tahun. Bagi pengunjung mancanegara, harga tiket masuknya adalah USD 25 untuk dewasa dan USD 15 untuk anak-anak usia 3-10 tahun. Harga tiket ini dapat berubah sewaktu-waktu, jadi disarankan untuk selalu memeriksa situs resmi atau menghubungi pihak pengelola sebelum berkunjung untuk mendapatkan informasi terbaru. Tiket tersebut umumnya mencakup akses ke kompleks utama candi serta beberapa area sekitarnya. Selain itu, pengunjung diharapkan mematuhi protokol kesehatan yang berlaku, seperti penggunaan masker dan menjaga jarak fisik selama berada di lokasi.",
    description3: "Setiap tahun, kompleks Candi Prambanan menjadi tuan rumah berbagai festival budaya, salah satunya adalah pertunjukan Ramayana Ballet yang diadakan di teater terbuka dengan latar belakang candi yang megah. Pertunjukan ini menggabungkan tari, musik, dan drama untuk menceritakan kisah epik Ramayana dengan latar yang sangat memukauww",
    img1: "",
    vidURL: "https://www.youtube.com/embed/sDNHiBHMG8s?si=GSGO71TZ1pufGts5",
    vidTitle: "Candi Prambanan dari Angkasa, oleh KOMPASTV",
    alamat: "Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55571",
    maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1976.6779668409188!2d110.48908559839477!3d-7.7520205999999865!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5ae3dbd859d1%3A0x19e7a03b25955a2d!2sPrambanan%20Temple!5e0!3m2!1sen!2sid!4v1716104050721!5m2!1sen!2sid'
  },
    {
      id: 1,
      name: "Malioboro",
      imgURL: "https://atourin.obs.ap-southeast-3.myhuaweicloud.com/images/destination/yogyakarta/titik-nol-km-jogja-profile1646131657.png?x-image-process=image/resize,p_100,limit_1/imageslim",
      title1: "Siapa yang ngga tau Malioboro?",
      title2: "Asal-usul dan Sejarah",
      title3: "Daya Tarik Malioboro",
      description1: 'Malioboro adalah salah satu jalan paling terkenal di Yogyakarta, Indonesia, dan merupakan jantung dari pusat kota yang sangat dinamis. Jalan ini terkenal sebagai destinasi wisata utama yang menawarkan berbagai pengalaman budaya, belanja, dan kuliner yang khas. ',
      description2: 'Malioboro Market memiliki berbagai macam makanan, pakaian, dan tempat menarik yang menjadi daya tariknya. Siapa yang tidak tahu Malioboro, pusat Kota Yogyakarta? Tempat wisata populer di Jogja yang disukai wisatawan Malioboro sekarang menjadi objek wisata yang menarik, meskipun pada awalnya hanya sebuah jalan biasa yang dipenuhi oleh pedagang kaki lima dan deretan toko. Karena Malioboro tidak boleh dilalui oleh kendaraan roda dua atau empat, jalannya tidak pernah macet meskipun ramai pengunjung. Ini memungkinkan pengunjung berwisata dan menikmati Malioboro dengan bebas. Yogyakarta terkenal dengan suasana malamnya yang indah dengan gemerlap lampu perumahan yang menciptakan nuansa yang syahdu.',
      description3: "Nama Malioboro diyakini berasal dari bahasa Sansekerta yang berarti karangan bunga. Ada juga teori lain yang menyebutkan bahwa nama ini berasal dari nama seorang pejabat kolonial Inggris, Marlborough, yang pernah tinggal di daerah ini. Malioboro terletak di pusat kota Yogyakarta dan membentang sepanjang lebih dari satu kilometer dari Stasiun Tugu di utara hingga ke persimpangan dengan Jalan Ahmad Yani di selatan. Jalan ini berdekatan dengan Keraton Yogyakarta, Benteng Vredeburg, dan Pasar Beringharjo, menjadikannya pusat aktivitas turis dan penduduk lokal",
      description4: 'Malioboro tidak terlalu ramai pada siang hari, tetapi menjelang malam, wisatawan mulai berdatangan dan menjelajahi jalan-jalannya. Jalan Malioboro memiliki banyak kafe dan restoran menarik, dan Anda juga dapat mencicipi makanan enak dan murah sepanjang jalan. Kamu dapat menikmati jalan-jalan santai bersama teman, pasangan, atau keluarga selain berbagai makanan dan minuman lezat. Liburan Anda akan menjadi lebih berkesan jika Anda berada di dekat orang tercinta Anda. Malioboro Jogja bukan hanya tempat untuk menikmati suasana kota yang khas, tetapi juga menawarkan banyak aktivitas seru dan menyenangkan bagi pengunjung. Beberapa hal menarik yang bisa dilakukan, seperti berfoto di spot yang instagrammable, berbelanja, naik delman, dan masih banyak lagi.  ',
      img1: "",
      img2: "https://www.riantybatik.co.id/blog/wp-content/uploads/2021/11/Kawasan-Malioboro-Yogyakarta-Memiliki-Daya-Magic-6.jpg",
      vidURL: "https://www.youtube.com/embed/UTLfIz09HsU?si=-7n10ebXShmErvFi",
      vidTitle: "Suasana Malioboro saat Libur Lebaran, oleh Jalan Amrita",
      alamat: "Sosromenduran, Gedong Tengen, Yogyakarta City, Special Region of Yogyakarta",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.9732522108084!2d110.36097984298708!3d-7.792656572247243!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5825fa6106c5%3A0x3ea4c521a5ed1133!2sJl.%20Malioboro%2C%20Sosromenduran%2C%20Gedong%20Tengen%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta!5e0!3m2!1sen!2sid!4v1716104816744!5m2!1sen!2sid'
    },
    {
      id: 2,
      name: "Alun-alun Yogyakarta",
      imgURL: "https://jogjakeren.com/wp-content/uploads/2022/08/alun-alun-utara.jpg",
      title0: "Seperti apa sih Alun-alun Yogyakarta?",
      title1: "Alun-Alun Utara",
      title2: "Alun-Alun Selatan",
      title3: "Sejarah",
      description1: 'Alun-Alun Yogyakarta adalah bagian penting dari budaya dan kehidupan masyarakat Yogyakarta. Alun-Alun merupakan lapangan luas yang berfungsi sebagai ruang publik dan memiliki peran penting dalam berbagai kegiatan sosial dan budaya. Di Yogyakarta, terdapat dua alun-alun utama, yaitu Alun-Alun Utara dan Alun-Alun Selatan.      ',
      description2: 'Alun-Alun Utara terletak di depan Keraton Yogyakarta dan berfungsi sebagai tempat berlangsungnya berbagai acara resmi kerajaan serta kegiatan kebudayaan. Alun-Alun Utara digunakan untuk berbagai upacara resmi kerajaan, seperti Grebeg Maulud, Grebeg Syawal, dan Grebeg Besar. Selain upacara kerajaan, alun-alun ini juga digunakan untuk berbagai kegiatan masyarakat seperti pasar malam, pameran, dan festival. Pada hari-hari tertentu, terutama selama perayaan besar, alun-alun ini menjadi pusat kegiatan masyarakat dengan pasar malam dan berbagai atraksi.',
      description3: "Alun-alun Selatan atau Alun-Alun Kidul adalah sebuah landmark berupa tanah lapang yang tidak bisa dipisahkan dengan Keraton Yogyakarta. Tanah Alun-alun ini berukuran 150m x 150m. Alun-alun Selatan Yogyakarta memiliki lima pintu masuk dan dilindungi oleh tembok. Jalan Langenastran Kidul, Jalan Langenastran Lor, Jalan Ngadisuryan, Jalan Patehan Lor, dan Jalan Gading melambangkan kelima indera manusia. Keraton memiliki kandang gajah di sisi barat atau di dekat Jalan Ngadisuryan.",
      description4: 'Alun-alun Kidul Yogyakarta, yang juga dikenal sebagai Alun-alun Pangkeran, dibangun selama pemerintahan Sri Sultan Hamengkubuwono I dari tahun 1755 hingga 1792. Ini juga merupakan tempat di mana para prajurit Keraton berlatih sebelum tradisi Garebeg dilakukan. Tempat ini dulunya sepi dan menakutkan. Selain itu, ada dua pohon beringin kembarnya. Alun-alun ini masih memiliki banyak aset utama, seperti pohon beringin, kweni, pakel, dan gayam, meskipun sekarang lebih ramai, bersih, dan diatur dengan baik. Masyarakat Jawa menganggap deretan pohon ini sebagai simbol keamanan, ketentraman, dan keteduhan. Selain pohon, tujuh pintu masuk alun-alun ini masih dipertahankan. Di sisi selatan terdapat Plengkung Gading, di sisi timur terdapat Jalan Langenarjan dan Jalan Langenastran, lalu Jalan Pamengkang, dan di sisi barat terdapat Jalan Ngadisuryan dan Jalan Patehan. Di salah satu sudut alun-alun ini, tepatnya di tempat tiga tiang yang terpancang dulunya diikat gajah raja. Sekarang, gajah itu hanya dikandangkan, dirias, dan dikeluarkan tiap kali upacara Gerebeg. Di sisi utara Alun-alun Kidul, di depan Siti Hinggil, terdapat deretan ubin batu bata yang dulunya digunakan sebagai tempat raja menyaksikan latihan prajurit.',
      img0: 'https://awsimages.detik.net.id/community/media/visual/2022/01/06/viral-dijual-virtual-begini-kondisi-terkini-alun-alun-utara-yogya-1_169.jpeg?w=1200',
      img1: "https://asset.kompas.com/crops/E8Fmi9dZr3GPgWanOf4m-QSDDyg=/0x0:749x500/750x500/data/photo/2023/03/11/640c446763daa.jpg",
      img2: "",
      vidURL: "https://www.youtube.com/embed/r-4QESXQ-8E?si=Zpt1mfsFZyk2waJ_",
      vidTitle: "Alun-alun Yogyakarta pada Malam Hari, oleh 4k Walk Pedestrian Traveler",
      maps: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.7915437508327!2d110.35833984298847!3d-7.811878172180521!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5739525ede4d%3A0x1759713f6a304135!2sAlun-Alun%20Kidul%20Yogyakarta!5e0!3m2!1sen!2sid!4v1716106345622!5m2!1sen!2sid',
      alamat: "Patehan, Kraton, Yogyakarta City, Special Region of Yogyakarta 55133",
    },
    {
      id: 3,
      name: "Candi Ratu Boko",
      imgURL: "https://upload.wikimedia.org/wikipedia/commons/7/77/Kraton_Ratu_Boko_%28Ratu_Boko_Temple%29_in_Yogyakarta%2C_Indonesia_03.jpg",
      title0: "Apa itu Candi Ratu Boko?",
      title1: "Sejarah Candi Ratu Boko",
      title2: "Rute menuju Tebing Breksi",
  
      description1: 'Candi Ratu Boko adalah sebuah situs purbakala yang terletak di dekat Yogyakarta, tepatnya sekitar 3 km di sebelah selatan dari kompleks Candi Prambanan. Meski sering disebut "candi," Ratu Boko sebenarnya lebih mirip sebuah istana atau keraton ketimbang candi biasa, dengan sisa-sisa bangunan yang menunjukkan bekas kompleks kerajaan atau pemukiman.',
      description2: 'Situs ini diperkirakan berasal dari abad ke-8 dan ke-9, dan didirikan oleh dinasti Syailendra atau Mataram Kuno. Nama Ratu Boko sendiri berasal dari legenda setempat tentang seorang raja yang disebut Raja Boko, ayah dari Roro Jonggrang, yang juga terkait dengan legenda Candi Prambanan.',
      description3: "Situs Ratu Boko berlokasi sekitar 18 km dari pusat kota Yogyakarta dan dapat dicapai dengan mudah menggunakan kendaraan pribadi atau transportasi umum. Kompleks ini telah dilengkapi dengan berbagai fasilitas untuk pengunjung, termasuk area parkir, pusat informasi, dan alur pejalan kaki yang nyaman. ",
      img1: "https://o-cdn-cas.sirclocdn.com/parenting/images/Candi-ratu-boko-jogja.width-800.format-webp.webp",
      img2: "",
      vidURL: "https://www.youtube.com/embed/cc7q9QvIYYg?si=qeP62aa-dSiKAH8R",
      vidTitle: "#DiIndonesiaAja | Pesona Ratu Boko, Tak Hanya Indah, Tapi Juga Kaya Sejarah oleh Pesona Indonesia",
      alamat: "Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 5572",
      maps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.1817624072182!2d110.48684087500483!3d-7.770541592248861!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5a92d354fe45%3A0x153f44f14476f95b!2sRatu%20Boko%20Temple!5e0!3m2!1sen!2sid!4v1716106915881!5m2!1sen!2sid"
    },
    {
      id: 4,
      name: "Tebing Breksi",
      imgURL: "https://njogja.co.id/wp-content/uploads/2023/11/Tebing-Breksi-6.webp",
      title0: "Destinasi yang Worth It untuk dikunjungi!",
      title1: "Apa itu Tebing Breksi?",
      title2: "Rute menuju Tebing Breksi",
  
      description1: 'Tebing Breksi adalah sebuah destinasi wisata alam yang terletak di Kabupaten Sleman, Yogyakarta, Indonesia. Tempat ini dikenal karena formasi batuannya yang unik dan pemandangan indah yang ditawarkan. Tebing Breksi merupakan salah satu tempat wisata yang relatif baru namun telah menjadi populer di kalangan wisatawan lokal maupun mancanegara.',
      description2: 'Tebing Breksi awalnya adalah sebuah tambang batu kapur yang dikelola oleh masyarakat setempat. Pada tahun 2014, kegiatan penambangan dihentikan karena area tersebut dinyatakan sebagai cagar budaya geologi. Batuan kapur di Tebing Breksi terbentuk dari material vulkanik Gunung Api Purba Nglanggeran, menjadikannya unik dari segi geologi.',
      description3: "Tebing Breksi terletak di Dusun Groyokan, Kelurahan Sambirejo, Kecamatan Prambanan, Kabupaten Sleman, Yogyakarta. Jaraknya sekitar 15 km dari pusat kota Yogyakarta dan dapat dicapai dengan kendaraan pribadi atau transportasi umum. Rute menuju Tebing Breksi juga searah dengan beberapa tempat wisata lain seperti Candi Ijo dan Candi Prambanan.",
      img1: "https://nagantour.com/wp-content/uploads/2023/08/taman-tebing-breksi.webp",
      img2: "",
      vidURL: "https://www.youtube.com/embed/H2tBk_uUIuo?si=SMznxYN9II9S5AiK",
      vidTitle: "Tebing Breksi Yogyakarta Update terbaru September 2023 oleh Jogjanesta Official",
      alamat: "Jl. Desa Lengkong, RT.02/RW.17, Gn. Sari, Sambirejo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55572",
      maps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3953.0712460485634!2d110.50194707500495!3d-7.7822709422374015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5aa458b4665b%3A0xa4b0fc6ad0ae38c7!2sTebing%20Breksi!5e0!3m2!1sen!2sid!4v1716106139758!5m2!1sen!2sid"
    },
    {
      id: 5,
      name: " Museum Ullen Sentalu",
      imgURL: "https://casaindonesia.com/lkgallery/teaser/ullen_teaser_46_201901171654348z7kfe.jpg",
      title0: "Museum Ullen Sentalu itu apa?",
      title1: "Sejarah Singkat",
      title2: "Pemandangan yang ciamik!",
      title3: "Tiket Masuk Museum Ullen Sentalu",
      description1: 'Museum Ullen Sentalu adalah sebuah museum seni dan budaya Jawa yang terletak di Kaliurang, Yogyakarta, Indonesia. Nama "Ullen Sentalu" merupakan singkatan dari "Ulating Blencong Sejatine Tataraning Lumaku," yang berarti "cahaya lampu blencong sebagai penunjuk jalan manusia dalam melangkah dan meniti kehidupan." Museum ini didedikasikan untuk melestarikan dan memamerkan warisan budaya serta sejarah Jawa, khususnya budaya keraton di Yogyakarta dan Surakarta.',
      description2: 'Museum Ullen Sentalu didirikan oleh keluarga Haryono pada tahun 1994 dan dibuka untuk umum pada tahun 1997. Terletak di kawasan pegunungan yang sejuk di Kaliurang, museum ini dibangun dengan konsep arsitektur yang menyatu dengan alam, menampilkan bangunan-bangunan yang terbuat dari batu dan terletak di tengah-tengah taman yang indah.',
      description3: "Museum Ullen Sentalu terletak di Jalan Boyong, Kaliurang, sekitar 25 kilometer dari pusat kota Yogyakarta. Lokasinya yang berada di dataran tinggi menawarkan suasana sejuk dan pemandangan alam yang indah. Museum ini dapat dicapai dengan kendaraan pribadi atau transportasi umum, dan tersedia area parkir yang memadai bagi pengunjung.",
      description4: 'Harga tiket masuk ke Museum Ullen Sentalu, sebuah destinasi budaya yang menakjubkan di Yogyakarta, bergantung pada status pengunjung dan jenis paket yang dipilih. Untuk pengunjung dewasa, tiket masuk berkisar antara [harga] sedangkan untuk anak-anak dan pelajar, tiket masuk memiliki tarif yang lebih terjangkau. Museum ini menawarkan pengalaman yang kaya akan sejarah, seni, dan budaya Jawa melalui koleksi yang luar biasa, termasuk artefak, lukisan, dan pameran interaktif. Dengan fasilitas yang modern dan panduan yang ramah, Museum Ullen Sentalu menjadi destinasi yang wajib dikunjungi bagi mereka yang ingin mengeksplorasi kekayaan warisan budaya Indonesia.',
      img1: "https://asset-2.tstatic.net/travel/foto/bank/images/spot-di-museum-ullen-sentalu.jpg",
      img2: "",
      vidURL: "https://www.youtube.com/embed/P5x01g1mBqg?si=8XNIWY6LVa0W1ljY",
      vidTitle: "Review Museum Yang Paling Indah di Jogja,ULLEN SENTALU & BEUKENHOF Resto oleh Elocer Channel",
      alamat: "Jl. Boyong No.KM 25, Kaliurang, Hargobinangun, Kec. Pakem, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55582",
      maps: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3954.786239734027!2d110.42025007500298!3d-7.5982279924166045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a5e02fd790ab9%3A0xa3fe6035b0792671!2sMuseum%20Ullen%20Sentalu!5e0!3m2!1sen!2sid!4v1716105125278!5m2!1sen!2sid"
    },
];

export default infowisata;
